#spring
spring:
  datasource: 
     url: jdbc:h2:tcp://localhost/~/jpashop 
     username: sa 
     password:
     driver-class-name: org.h2.Driver
  jpa: 
    hibernate: 
      ddl-auto: create 
    properties: 
      hibernate: 
        #show_sql: true 
        format_sql: true
        default_batch_fetch_size: 100  #this is for jpa collection query..very important
  Output:
    ansi:
      enabled: always
        
#logging         
logging.level: 
  org.hibernate.SQL: debug 
  org.hibernate.type: trace 